# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
#
name: Test

# Trigger the workflow's on all PRs but only on pushed tags or commits to
# main/master branch to avoid PRs developed in a GitHub fork's dedicated branch
# to trigger.
on:
  pull_request:
  push:
    branches:
    tags:
  workflow_dispatch:

defaults:
  run:
    # Declare bash be used by default in this workflow's "run" steps.
    #
    # NOTE: bash will by default run with:
    #   --noprofile: Ignore ~/.profile etc.
    #   --norc:      Ignore ~/.bashrc etc.
    #   -e:          Exit directly on errors
    #   -o pipefail: Don't mask errors from a command piped into another command
    shell: bash

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      # Keep running even if one variation of the job fail
      fail-fast: false
      matrix:
        # We run this job multiple times with different parameterization
        # specified below, these parameters have no meaning on their own and
        # gain meaning on how job steps use them.
        # 0 is a placeholder that indicates jupyter-server should be tested on its own
        jupyterlab_version: [0, 1, 2, 3]
        python: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"
      - name: Build Python package
        id: build-package
        run: |
          pip install jupyter_packaging wheel jupyterlab
          python setup.py sdist bdist_wheel
      - name: Install Python dependencies
        # NOTE: See CONTRIBUTING.md for a local development setup that differs
        #       slightly from this.
        run: |
          pip install --upgrade pip
          pip install jupyter_packaging jupyterlab~=${{ matrix.jupyterlab_version }}.0
          pip install ./dist/jupyter_server_proxy-*.whl
          pip install pytest
          pip freeze
      - name: Run tests
        run: |
          if [ ${{ matrix.jupyterlab_version }} -gt 0 ]; then
              APP=notebook
          else
              APP=server
          fi
          JUPYTER_TOKEN=secret jupyter-$APP --config=./tests/resources/jupyter_server_config.py &
          sleep 5
          pytest --verbose --color=yes

      - name: Check the Notebook Server extension is installed
        run: |
          jupyter serverextension list 2>&1 | grep -ie "jupyter_server_proxy.*enabled" -

      - name: Check the Jupyter Server extension is installed
        run: |
          pip install jupyter-server
          jupyter server extension list 2>&1 | grep -ie "jupyter_server_proxy.*enabled" -
